### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by shasharoman** [rrfeng/lua-resty-upstream-etcd#2]
感谢作者提供这样的工具，我尝试按照README.md的指引对我本地的openresty进行完整配置，随后发现可以正常工作。

但这个过程中似乎存在一个不小的问题，偶尔出现通过etcdctl set新加入的upstream无法work，比如我动态加入前两个upsream，他们可以正常接受到nginx转发过来的流量，但继续添加时发现无法接收到流量，我重复尝试了几次，观察出现这种情况的概率不小。

``` shell
[linux:~ 00:05]$ etcdctl ls /upstream/dev
/upstream/dev/172.17.0.3:1024
/upstream/dev/172.17.0.4:1024
/upstream/dev/172.17.0.5:1024
[linux:~ 00:05]$ etcdctl get /upstream/dev/172.17.0.3:1024
{"weight":1,"slow_start":1,"status":"up"}
[linux:~ 00:05]$ etcdctl get /upstream/dev/172.17.0.4:1024
{"weight":1,"slow_start":1,"status":"up"}
[linux:~ 00:05]$ etcdctl get /upstream/dev/172.17.0.5:1024
{"weight":1,"slow_start":1,"status":"up"}
```

172.17.0.5:1024这个upstream收不到nginx转发过来的流量，这种情况非必现，由于我对openresty以及lua编程不是特别熟悉，所以review代码无法找出问题所在。

但据我观察，在我继续用etcdctl set时，syncer.fetch方法的url中waitIndex有递增，仅此而已...

不管怎样，感谢作者提供这样一个tools，对于学习openresty以及实现类似功能有莫大帮助，这个issue只是反馈一下我遇到的情况，让作者您知悉。

**Comment by rrfeng** [comment]
可以看下 nginx error log，如果没有更新成功可以看到报错的。
另外可以配置一个 location，通过 picker.show() 展示已经加入到 upstream 中的列表。

**Comment by shasharoman** [comment]
好的

**Comment by shasharoman** [comment]
好的
