### ISSUE TITLE
关于健康监测部分

### ISSUE THREAD

**Issue by gotosre** [rrfeng/lua-resty-upstream-etcd#3]
看代码，健康监测部分包括：
1. 主动检测
2. 基于过去访问的日志分析

---
有些问题想请教一下：
1. 假如没有passive检测，主动检测或者是日志检测，都有一定的时间间隔，如果间隔期间出现后端异常，那么该异常后端会继续存活至checkdown，如果量大的话，是不是会导致一定的pvlost呢？
2. logchecker的条件是status >= 400，但是4xx是端侧问题，根据这个判断peer异常，场景是？

**Comment by rrfeng** [comment]
> 看代码，健康监测部分包括：
> 
> 1. 主动检测
> 2. 基于过去访问的日志分析
> 
> 有些问题想请教一下：
> 
> 1. 假如没有passive检测，主动检测或者是日志检测，都有一定的时间间隔，如果间隔期间出现后端异常，那么该异常后端会继续存活至checkdown，如果量大的话，是不是会导致一定的pvlost呢？

不管什么类型的健康检查都是有时间间隔的，在这个间隔期间挂了那肯定会有 lost。理论上就没法避免。

> 2. logchecker的条件是status >= 400，但是4xx是端侧问题，根据这个判断peer异常，场景是？

这个是可配置的，按需修改就行了。
